//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Credentials
    {
        public int Account_ID { get; set; }
        public string Username_Key { get; set; }
        public string Username_Vector { get; set; }
        public string First_Name_Key { get; set; }
        public string First_Name_Vector { get; set; }
        public string Last_Name_Key { get; set; }
        public string Last_Name_Vector { get; set; }
        public string E_mail_Key { get; set; }
        public string E_mail_Vector { get; set; }
        public string Password_Key { get; set; }
        public string Password_Vector { get; set; }
    }
}
