//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CipherDBEntities : DbContext
    {
        public CipherDBEntities()
            : base("name=CipherDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Additions> Account_Additions { get; set; }
        public virtual DbSet<Account_Credentials> Account_Credentials { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Additions_Credentials> Additions_Credentials { get; set; }
        public virtual DbSet<Entry> Entries { get; set; }
        public virtual DbSet<Entries_Credentials> Entries_Credentials { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Fields_Credentials> Fields_Credentials { get; set; }
    }
}
