//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int ID { get; set; }
        public Nullable<int> Account_ID { get; set; }
        public string Name { get; set; }
        public string Additional_Info { get; set; }
    }
}
