//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fields_Credentials
    {
        public int Field_ID { get; set; }
        public string Name_Key { get; set; }
        public string Name_Vector { get; set; }
        public string Data_Key { get; set; }
        public string Data_Vector { get; set; }
    }
}
